import * as THREE from 'three';
import { TankDefinition } from './shared/tank-definition.type';
import parts from './shared/common-parts';
import challenger2 from './tanks/challenger-2';
import t55am1 from './tanks/t55am1';

export const TANK_DEFINITIONS: TankDefinition[] = [
  t55am1,
  {
    id: 't72b',
    name: 'T-72B',
    role: 'Low Profile Brawler',
    description: 'Soviet T-72 variant with improved composite protection, stronger gun-launched missile capability, and Kontakt-era armor upgrades.',
    origin: 'Developed in the Soviet Union as a major T-72 upgrade focused on armor protection and battlefield survivability.',
    year: 1985,
    country: 'Soviet Union',
    modelPath: '/battletanks/tanks/t72b/scene.gltf',
    visualTargetLength: 76,
    visualRotation: new THREE.Euler(0, 0, 0),
    parts,
  },
  {
    id: 'm1-abrams',
    name: 'M1A2 Abrams',
    role: 'Desert MBT',
    description: 'American Abrams upgrade introducing improved digital systems, commander thermal sight, and enhanced battlefield awareness.',
    origin: 'Developed in the United States as the digitalized M1 Abrams evolution for modern armored warfare.',
    year: 1992,
    country: 'United States',
    modelPath: '/battletanks/tanks/m1-abrams/scene.gltf',
    visualTargetLength: 86,
    visualRotation: new THREE.Euler(0, 0, 0),
    parts,
  },
  {
    id: 'leopard-2a6',
    name: 'Leopard 2A6',
    role: 'Long Gun Sniper',
    description: 'German Leopard 2 upgrade centered around the longer Rheinmetall 120 mm L/55 gun and improved protection packages.',
    origin: 'Developed in Germany from the Leopard 2A5 as a firepower-focused upgrade for greater long-range performance.',
    year: 2001,
    country: 'Germany',
    modelPath: '/battletanks/tanks/leopard-2a6/scene.gltf',
    visualTargetLength: 82,
    visualRotation: new THREE.Euler(0, 0, 0),
    parts,
  },
  {
    id: 'merkava-mk4',
    name: 'Merkava Mk.4',
    role: 'Defender',
    description: 'Israeli Merkava generation with modular armor, advanced electronics, and design emphasis on crew protection.',
    origin: 'Developed in Israel as the fourth major Merkava generation, continuing the front-engine layout and survivability-first doctrine.',
    year: 2004,
    country: 'Israel',
    modelPath: '/battletanks/tanks/merkava-mk4/scene.gltf',
    visualTargetLength: 80,
    visualRotation: new THREE.Euler(0, 0, 0),
    parts,
  },
  challenger2,
  {
    id: 'leclerc',
    name: 'Leclerc',
    role: 'Fast Autoloader',
    description: 'French main battle tank with an autoloader, compact crew arrangement, and strong mobility for its class.',
    origin: 'Developed in France by GIAT Industries to replace the AMX-30 with a modern, highly automated MBT.',
    year: 1992,
    country: 'France',
    modelPath: '/battletanks/tanks/leclerc/scene.gltf',
    visualTargetLength: 76,
    visualRotation: new THREE.Euler(0, 0, 0),
    parts,
  },
  {
    id: 'k2-black-panther',
    name: 'K2 Black Panther',
    role: 'Tech Striker',
    description: 'South Korean main battle tank with advanced fire control, active suspension, and modern composite armor.',
    origin: 'Developed in South Korea by Hyundai Rotem as a domestic next-generation MBT for the Republic of Korea Army.',
    year: 2014,
    country: 'South Korea',
    modelPath: '/battletanks/tanks/k2-black-panther/scene.gltf',
    visualTargetLength: 78,
    visualRotation: new THREE.Euler(0, 0, 0),
    parts,
  },
  {
    id: 'type-10',
    name: 'Type 10',
    role: 'Light MBT',
    description: 'Japanese lightweight main battle tank designed for mobility, modular armor, and modern networked combat.',
    origin: 'Developed in Japan by Mitsubishi Heavy Industries to complement and eventually replace older Type 74 and Type 90 tanks.',
    year: 2012,
    country: 'Japan',
    modelPath: '/battletanks/tanks/type-10/scene.gltf',
    visualTargetLength: 72,
    visualRotation: new THREE.Euler(0, 0, 0),
    parts,
  },
  {
    id: 'm60-patton',
    name: 'M60 Patton',
    role: 'Retro Heavy',
    description: 'American Cold War main battle tank evolved from the M48 Patton line with a 105 mm gun and improved hull.',
    origin: 'Developed in the United States as a rapid evolution of the Patton series during the early Cold War.',
    year: 1960,
    country: 'United States',
    modelPath: '/battletanks/tanks/m60-patton/scene.gltf',
    visualTargetLength: 76,
    visualRotation: new THREE.Euler(0, 0, 0),
    parts,
  },
  {
    id: '7tp',
    name: '7TP',
    role: 'Interwar Light Tank',
    description: 'Polish light tank developed from the Vickers 6-ton design, noted for its diesel engine and 37 mm Bofors gun.',
    origin: 'Developed in Poland by Panstwowe Zaklady Inzynierii as a domestic improvement of the British Vickers 6-ton tank.',
    year: 1935,
    country: 'Poland',
    modelPath: '/battletanks/tanks/7tp/scene.gltf',
    visualTargetLength: 54,
    visualRotation: new THREE.Euler(0, 0, 0),
    parts,
  },
  {
    id: '10tp',
    name: '10TP',
    role: 'Prototype Cruiser',
    description: 'Polish fast tank prototype using Christie-style suspension concepts and a compact pre-war turret layout.',
    origin: 'Developed in Poland as an experimental high-speed cruiser tank program before World War II.',
    year: 1938,
    country: 'Poland',
    modelPath: '/battletanks/tanks/10tp/scene.gltf',
    visualTargetLength: 60,
    visualRotation: new THREE.Euler(0, 0, 0),
    parts,
  },
  {
    id: 'pt91-twardy',
    name: 'PT-91 Twardy',
    role: 'Polish MBT',
    description: 'Polish T-72M1 modernization with ERAWA reactive armor, improved fire control, and local systems upgrades.',
    origin: 'Developed in Poland by OBRUM and Bumar-Labedy from the T-72M1 as a domestic main battle tank modernization.',
    year: 1995,
    country: 'Poland',
    modelPath: '/battletanks/tanks/pt91-twardy/scene.gltf',
    visualTargetLength: 76,
    visualRotation: new THREE.Euler(0, 0, 0),
    parts,
  },
  {
    id: 'leopard-2pl',
    name: 'Leopard 2PL',
    role: 'Polish Upgrade',
    description: 'Polish modernization of Leopard 2A4 tanks with improved turret armor, optics, and onboard systems.',
    origin: 'Developed for Poland as an upgrade package for Polish Leopard 2A4 tanks with domestic and German industry involvement.',
    year: 2020,
    country: 'Poland',
    modelPath: '/battletanks/tanks/leopard-2pl/scene.gltf',
    visualTargetLength: 82,
    visualRotation: new THREE.Euler(0, 0, 0),
    parts,
  },
  {
    id: 'pl-01',
    name: 'PL-01 Concept',
    role: 'Stealth Concept',
    description: 'Polish concept light tank/direct-fire vehicle with a futuristic low-profile unmanned turret presentation.',
    origin: 'Presented in Poland by OBRUM and BAE Systems as a technology demonstrator for a stealthy future armored vehicle.',
    year: 2013,
    country: 'Poland',
    modelPath: '/battletanks/tanks/pl-01/scene.gltf',
    visualTargetLength: 74,
    visualRotation: new THREE.Euler(0, 0, 0),
    parts,
  },
];

export const DEFAULT_TANK_ID = TANK_DEFINITIONS[0].id;

export const getTankDefinition = (id: string | null | undefined): TankDefinition => (
    TANK_DEFINITIONS.find((definition) => definition.id === id) ?? TANK_DEFINITIONS[0]
);
