import type {TankDefinition, TankGameplayStats} from './tank-definition.type';

type TankDefinitionWithoutStats = Omit<TankDefinition, 'stats'> & Partial<Pick<TankDefinition, 'stats'>>;

const DEFAULT_TANK_GAMEPLAY_STATS: TankGameplayStats = {
  hasRotatingTurret: true,
  maxHealth: 100,
  defense: 0.12,
  moveSpeed: 100,
  turnSpeed: 1,
  turretTraverseDegPerSecond: 72,
  aimPitchDegPerSecond: 42,
  bulletDamage: 10,
  bulletSpeed: 680,
  fireCooldownMs: 420,
  mainWeapon: 'Tank gun',
  traits: ['balanced'],
};

export const TANK_GAMEPLAY_STATS: Record<string, TankGameplayStats> = {
  t55am1: {
    hasRotatingTurret: true,
    maxHealth: 105,
    defense: 0.18,
    moveSpeed: 96,
    turnSpeed: 0.98,
    turretTraverseDegPerSecond: 58,
    aimPitchDegPerSecond: 38,
    bulletDamage: 11,
    bulletSpeed: 690,
    fireCooldownMs: 460,
    mainWeapon: '100 mm D-10T gun',
    secondaryWeapon: 'Coaxial machine gun',
    traits: ['reliable', 'medium armor'],
  },
  t72b: {
    hasRotatingTurret: true,
    maxHealth: 122,
    defense: 0.28,
    moveSpeed: 102,
    turnSpeed: 1,
    turretTraverseDegPerSecond: 54,
    aimPitchDegPerSecond: 36,
    bulletDamage: 15,
    bulletSpeed: 730,
    fireCooldownMs: 520,
    mainWeapon: '125 mm 2A46M gun',
    specialWeapon: 'Gun-launched missile fit',
    traits: ['low profile', 'reactive armor'],
  },
  'm1-abrams': {
    hasRotatingTurret: true,
    maxHealth: 135,
    defense: 0.32,
    moveSpeed: 112,
    turnSpeed: 1.02,
    turretTraverseDegPerSecond: 76,
    aimPitchDegPerSecond: 44,
    bulletDamage: 16,
    bulletSpeed: 790,
    fireCooldownMs: 470,
    mainWeapon: '120 mm M256 smoothbore',
    secondaryWeapon: 'Commander machine gun',
    traits: ['heavy armor', 'fast turret'],
  },
  'leopard-2a6': {
    hasRotatingTurret: true,
    maxHealth: 128,
    defense: 0.29,
    moveSpeed: 116,
    turnSpeed: 1.08,
    turretTraverseDegPerSecond: 74,
    aimPitchDegPerSecond: 45,
    bulletDamage: 17,
    bulletSpeed: 820,
    fireCooldownMs: 460,
    mainWeapon: '120 mm L/55 smoothbore',
    traits: ['long gun', 'accurate'],
  },
  'merkava-mk4': {
    hasRotatingTurret: true,
    maxHealth: 145,
    defense: 0.34,
    moveSpeed: 98,
    turnSpeed: 0.94,
    turretTraverseDegPerSecond: 66,
    aimPitchDegPerSecond: 40,
    bulletDamage: 16,
    bulletSpeed: 760,
    fireCooldownMs: 500,
    mainWeapon: '120 mm MG253 smoothbore',
    secondaryWeapon: 'Remote weapon station',
    traits: ['crew protection', 'survivor'],
  },
  'challenger-2': {
    hasRotatingTurret: true,
    maxHealth: 150,
    defense: 0.36,
    moveSpeed: 92,
    turnSpeed: 0.88,
    turretTraverseDegPerSecond: 62,
    aimPitchDegPerSecond: 38,
    bulletDamage: 16,
    bulletSpeed: 740,
    fireCooldownMs: 530,
    mainWeapon: '120 mm L30A1 rifled gun',
    traits: ['heavy armor', 'rifled gun'],
  },
  leclerc: {
    hasRotatingTurret: true,
    maxHealth: 118,
    defense: 0.23,
    moveSpeed: 124,
    turnSpeed: 1.12,
    turretTraverseDegPerSecond: 78,
    aimPitchDegPerSecond: 46,
    bulletDamage: 15,
    bulletSpeed: 790,
    fireCooldownMs: 360,
    mainWeapon: '120 mm CN120-26 smoothbore',
    specialWeapon: 'Autoloader',
    traits: ['autoloader', 'mobile'],
  },
  'k2-black-panther': {
    hasRotatingTurret: true,
    maxHealth: 125,
    defense: 0.27,
    moveSpeed: 126,
    turnSpeed: 1.14,
    turretTraverseDegPerSecond: 80,
    aimPitchDegPerSecond: 48,
    bulletDamage: 16,
    bulletSpeed: 800,
    fireCooldownMs: 440,
    mainWeapon: '120 mm L/55 smoothbore',
    specialWeapon: 'Active suspension',
    traits: ['agile MBT', 'high tech'],
  },
  'type-10': {
    hasRotatingTurret: true,
    maxHealth: 108,
    defense: 0.19,
    moveSpeed: 132,
    turnSpeed: 1.2,
    turretTraverseDegPerSecond: 82,
    aimPitchDegPerSecond: 48,
    bulletDamage: 14,
    bulletSpeed: 780,
    fireCooldownMs: 400,
    mainWeapon: '120 mm smoothbore',
    traits: ['light MBT', 'rapid response'],
  },
  'm60-patton': {
    hasRotatingTurret: true,
    maxHealth: 110,
    defense: 0.2,
    moveSpeed: 86,
    turnSpeed: 0.92,
    turretTraverseDegPerSecond: 56,
    aimPitchDegPerSecond: 36,
    bulletDamage: 12,
    bulletSpeed: 700,
    fireCooldownMs: 480,
    mainWeapon: '105 mm M68 gun',
    traits: ['old MBT', 'steady gun'],
  },
  '7tp': {
    hasRotatingTurret: true,
    maxHealth: 65,
    defense: 0.05,
    moveSpeed: 104,
    turnSpeed: 1.24,
    turretTraverseDegPerSecond: 52,
    aimPitchDegPerSecond: 36,
    bulletDamage: 7,
    bulletSpeed: 590,
    fireCooldownMs: 320,
    mainWeapon: '37 mm Bofors gun',
    secondaryWeapon: '7.92 mm machine gun',
    traits: ['small', 'interwar'],
  },
  '10tp': {
    hasRotatingTurret: true,
    maxHealth: 70,
    defense: 0.04,
    moveSpeed: 145,
    turnSpeed: 1.34,
    turretTraverseDegPerSecond: 54,
    aimPitchDegPerSecond: 38,
    bulletDamage: 7,
    bulletSpeed: 600,
    fireCooldownMs: 300,
    mainWeapon: '37 mm Bofors gun',
    traits: ['fast prototype', 'light armor'],
  },
  'pt91-twardy': {
    hasRotatingTurret: true,
    maxHealth: 124,
    defense: 0.3,
    moveSpeed: 104,
    turnSpeed: 1,
    turretTraverseDegPerSecond: 58,
    aimPitchDegPerSecond: 38,
    bulletDamage: 15,
    bulletSpeed: 735,
    fireCooldownMs: 500,
    mainWeapon: '125 mm 2A46 gun',
    specialWeapon: 'ERAWA reactive armor',
    traits: ['reactive armor', 'polish MBT'],
  },
  'leopard-2pl': {
    hasRotatingTurret: true,
    maxHealth: 132,
    defense: 0.31,
    moveSpeed: 110,
    turnSpeed: 1.02,
    turretTraverseDegPerSecond: 72,
    aimPitchDegPerSecond: 44,
    bulletDamage: 16,
    bulletSpeed: 790,
    fireCooldownMs: 470,
    mainWeapon: '120 mm Rh-120 L/44 gun',
    traits: ['modernized armor', 'polish upgrade'],
  },
  'pl-01': {
    hasRotatingTurret: true,
    maxHealth: 95,
    defense: 0.16,
    moveSpeed: 128,
    turnSpeed: 1.18,
    turretTraverseDegPerSecond: 84,
    aimPitchDegPerSecond: 48,
    bulletDamage: 13,
    bulletSpeed: 760,
    fireCooldownMs: 390,
    mainWeapon: '105/120 mm concept gun',
    specialWeapon: 'Low-signature concept package',
    traits: ['stealth concept', 'low profile'],
  },
  'm18-hellcat': {
    hasRotatingTurret: true,
    maxHealth: 60,
    defense: 0.03,
    moveSpeed: 170,
    turnSpeed: 1.36,
    turretTraverseDegPerSecond: 36,
    aimPitchDegPerSecond: 38,
    bulletDamage: 14,
    bulletSpeed: 760,
    fireCooldownMs: 420,
    mainWeapon: '76 mm M1 gun',
    traits: ['glass cannon', 'superszybki'],
  },
  maus: {
    hasRotatingTurret: true,
    maxHealth: 190,
    defense: 0.48,
    moveSpeed: 46,
    turnSpeed: 0.45,
    turretTraverseDegPerSecond: 14,
    aimPitchDegPerSecond: 24,
    bulletDamage: 26,
    bulletSpeed: 540,
    fireCooldownMs: 1050,
    mainWeapon: '128 mm KwK 44 L/55 gun',
    secondaryWeapon: '75 mm coaxial gun',
    traits: ['super heavy', 'fortress'],
  },
  sturmtiger: {
    hasRotatingTurret: false,
    maxHealth: 150,
    defense: 0.34,
    moveSpeed: 55,
    turnSpeed: 0.58,
    turretTraverseDegPerSecond: 0,
    aimPitchDegPerSecond: 28,
    bulletDamage: 38,
    bulletSpeed: 360,
    fireCooldownMs: 1800,
    mainWeapon: '380 mm RW 61 rocket mortar',
    specialWeapon: 'Massive wall-breaking rocket',
    traits: ['siege weapon', 'no turret'],
  },
  'strv-103': {
    hasRotatingTurret: false,
    maxHealth: 100,
    defense: 0.2,
    moveSpeed: 108,
    turnSpeed: 1.08,
    turretTraverseDegPerSecond: 0,
    aimPitchDegPerSecond: 30,
    bulletDamage: 18,
    bulletSpeed: 850,
    fireCooldownMs: 520,
    mainWeapon: '105 mm Bofors L/62 gun',
    specialWeapon: 'Hull-aimed fixed gun',
    traits: ['turretless', 'sniper'],
  },
  'tks-20mm': {
    hasRotatingTurret: false,
    maxHealth: 45,
    defense: 0.02,
    moveSpeed: 155,
    turnSpeed: 1.55,
    turretTraverseDegPerSecond: 0,
    aimPitchDegPerSecond: 34,
    bulletDamage: 4,
    bulletSpeed: 720,
    fireCooldownMs: 110,
    mainWeapon: '20 mm wz.38 FK-A autocannon',
    secondaryWeapon: '7.92 mm machine gun',
    specialWeapon: 'Rapid 20 mm harassment fire',
    traits: ['tiny hitbox', 'autocannon'],
  },
};

export const tankStatsFor = (tankId: string): TankGameplayStats => (
  TANK_GAMEPLAY_STATS[tankId] ?? DEFAULT_TANK_GAMEPLAY_STATS
);

export const attachTankStats = (definition: TankDefinitionWithoutStats): TankDefinition => ({
  ...definition,
  stats: definition.stats ?? tankStatsFor(definition.id),
});
